[module/temperature]
type = internal/temperature
thermal-zone = 5
; Full path of temperature sysfs path
; Use `sensors` to find preferred temperature source, then run
; $ for i in /sys/class/hwmon/hwmon*/temp*_input; do echo "$(<$(dirname $i)/name): $(cat ${i%_*}_label 2>/dev/null || echo $(basename ${i%_*})) $(readlink -f $i)"; done
; to find path to desired file
; Default reverts to thermal zone settinghwmon-path = ./modules/temp
hwmon-path = ./modules/temp

warn-temperature = 65

format = <ramp> <label>
;format-underline = #f50a4d
format-warn = <ramp> <label-warn>
;format-warn-underline = ${self.format-underline}

label = %temperature-c%
label-warn = HOT! %temperature-c%
label-warn-foreground = #f00

ramp-0 =
ramp-1 =
ramp-2 =
ramp-foreground = #66
