[module/wireless-network]
type = internal/network
include-file = wireless-interface
# create file 'wireless-interface' with right interface name, syntax in line below
# interface = wlp4s0
interface-type = wlan
interval = 1.0
ping-interval = 10

format-connected = <label-connected>
label-connected = %{T3}󰖩%{T-} %local_ip%  %downspeed%  %upspeed%
label-disconnected = %{T3}󰖩%{T-} not connected
label-disconnected-foreground = #66

ramp-signal-0 = 
