[module/wired-network]
type = internal/network
include-file = wired-interface
# create file 'wired-interface' with right interface name, syntax in line below
# interface = enxd43a6527232f
interface-type = wired
interval = 1.0
ping-interval = 10

format-connected = <label-connected>
label-connected = %{T3}%{T-} %local_ip%  %downspeed%  %upspeed%
label-disconnected = %{T3}%{T-} not connected
label-disconnected-foreground = #66
