#!/bin/sh
lock() {
    dunstctl set-paused true
    i3lock -c 111111 -e -f -n
    dunstctl set-paused false
}

case "$1" in
lock)
    lock
    ;;
logout)
    i3-msg exit
    ;;
suspend)
    systemctl suspend && lock
    ;;
hibernate)
    lock && systemctl hibernate
    ;;
reboot)
    systemctl reboot
    ;;
shutdown)
    systemctl poweroff
    ;;
*)
    echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
    exit 2
    ;;
esac

exit 0
