#!/bin/bash -u
if [ "$(whoami)" = 'root' ]
then
    echo "No need to run this script as root"
    exit 1
fi

# Launch docker dns container
docker ps -a |grep "dns"
if [ $? -eq 0 ]
then
    docker start dns
else
    docker run --detach=true --volume=/var/run/docker.sock:/docker.sock \
        --publish=172.17.0.1:53:53/udp --name dns phensley/docker-dns --domain docker
fi
